// src/app/services/web/portfolioProjects.ts
export const portfolioProjects = [
  {
    title: 'Prepa Ibero',
    year: 2023,
    tags: ['Web'],
    image: '/img/prepa-ibero.svg',
    link: '#',
  },
  {
    title: 'Imemsa',
    year: 2022,
    tags: ['Web', 'Design'],
    image: '/img/imemsa.svg',
    link: '#',
  },
  {
    title: 'Venn',
    year: 2022,
    tags: ['Web', 'Design', 'Marketing'],
    image: '/img/venn.svg',
    link: '#',
  },
  {
    title: 'Biogal',
    year: 2023,
    tags: ['Web', 'Design'],
    image: '/img/biogal.svg',
    link: '#',
  },
  {
    title: 'Abastero',
    year: 2023,
    tags: ['Web', 'Design'],
    image: '/img/abastero.svg',
    link: '#',
  },
  {
    title: 'Optics Mx/Col',
    year: 2022,
    tags: ['Web', 'Marketing'],
    image: '/img/opticsmxcol.svg',
    link: '#',
  },
  {
    title: 'Mexbusa',
    year: 2022,
    tags: ['Web', 'Marketing'],
    image: '/img/mexbusa.svg',
    link: '#',
  },
  {
    title: 'Uniq Luxury',
    year: 2022,
    tags: ['Web'],
    image: '/img/uniqluxury.svg',
    link: '#',
  },
  {
    title: 'Decocuit',
    year: 2022,
    tags: ['Web'],
    image: '/img/decocuit.svg',
    link: '#',
  },
  {
    title: 'Commerce Society',
    year: 2022,
    tags: ['Web'],
    image: '/img/commerce-society.svg',
    link: '#',
  },
  {
    title: 'Kiki',
    year: 2022,
    tags: ['Web', 'Design', 'Marketing'],
    image: '/img/kiki.svg',
    link: '#',
  },
  {
    title: 'Voluntarios México',
    year: 2022,
    tags: ['Web', 'Design'],
    image: '/img/voluntarios-mexico.svg',
    link: '#',
  },
];
